# Критерий Колмогорова - Смирнова для простой гипотезы

In [1]:
import random
import math
from math import e
import numpy as np
import pandas as pd

In [2]:
def make_expon_viborka(n, lam = 0.8):
    lst = []
    for i in range(n):
        r = random.random()
        x = -math.log(r,math.e) / lam
        lst.append(float('{:.3f}'.format(x)))
    
    return lst

In [3]:
n = 1000 # объем выборки

In [4]:
# Создаем 2 выборки 
viborka_1 = make_expon_viborka(n)
viborka_2 = make_expon_viborka(n)

In [5]:
def count_amount(viborka_1,viborka_2, inter = 1):
    
    int_min1 = min(viborka_1)
    int_min2 = min(viborka_2)
    int_max1 = max(viborka_1)
    int_max2 = max(viborka_2)
    
    my_max = max(int_max1, int_max2) # максимальное и минимальное граница значений
    my_min = min(int_min1, int_min2)
    

    lower_border = 0 # картка для подсчета количество вхожденией
    upper_border = inter
    
    interval = [] # интервал
    interval1 = [] 
    interval2 = []
    
    while lower_border <= my_max + inter:
        interval.append(lower_border)
        lower_border += inter
    
    interval1 = interval[:-1]
    interval2 = interval[1:]
    
    #print('Int', interval)
    amount1 = [] # количество вхождений чисел в каждый отрезок
    amount2 = []
    
    vib1 = sorted(viborka_1)
    vib2 = sorted(viborka_2)
    '''
    print('v1', vib1)
    print('9:', vib1[9])
    print(len(vib1))
    print('v2', vib2)
    '''
    count1 = 0
    count2 = 0
    
    
    #-------------------------------------------------------------------------------------
    lower_border = 0 # каретка для подсчета количество вхожденией
    upper_border = inter
    
    k  = 0 
    #print('!', interval[-1])
    while lower_border < interval[-1]:
        
        if k >= len(vib1):
            amount1.append(count1)
            lower_border = upper_border
            upper_border += inter
            count1 = 0
            
        elif lower_border <= vib1[k] < upper_border:
            #print(lower_border,' < ', vib1[k], '<', upper_border)
            count1 += 1
            k += 1

        else:
            lower_border = upper_border
            upper_border += inter
            amount1.append(count1)
            count1 = 0
        '''
        print('----')
        print('lower', lower_border)
        print('upper', upper_border)
        print('k =', k)
        '''
    
    lower_border = 0 # картка для подсчета количество вхожденией
    upper_border = inter
    
    k = 0
    
    while lower_border < interval[-1]:
        
        if k >= len(vib2):
            amount2.append(count2)
            lower_border = upper_border
            upper_border += inter
            count2 = 0
        elif lower_border <= vib2[k] < upper_border:
            #print(lower_border,' < ', vib2[k], '<', upper_border)
            count2 += 1
            k += 1

        else:
            lower_border = upper_border
            upper_border += inter
            amount2.append(count2)
            count2 = 0
    
    
    res = [amount1, amount2, interval1, interval2]
    
    return res

In [6]:
count_amount(viborka_1, viborka_2)

[[515, 264, 117, 65, 21, 11, 2, 2, 3],
 [545, 260, 110, 49, 18, 10, 6, 1, 1],
 [0, 1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [7]:
am1, am2, inter1, inter2 = count_amount(viborka_1, viborka_2)
print(list(map(len, [am1, am2, inter1, inter2])))

[9, 9, 9, 9]

In [8]:
def table(viborka_1, viborka_2): 
    
    
    am1 = count_amount(viborka_1, viborka_2)[0]
    am2 = count_amount(viborka_1, viborka_2)[1]
    inter1 = count_amount(viborka_1, viborka_2)[2]
    inter2 = count_amount(viborka_1, viborka_2)[3]

    
    p = 0.8 # оценка парметра p
    
    print('Параметер равен: ', p)
    

    data = {'x_k': inter1,
           'x_k+1': inter2,
            'n_k_1': am1,
            'n_k_2': am2 }
    
    df = pd.DataFrame(data)
    n_im_list = []
    n_im_list_2 = []
    
    sum_k = 0 
    
    for k in range(len(am1)):
        sum_k += df.iloc[k]['n_k_1']
        n_im_list.append(sum_k)
    
    sum_k = 0 
    for k in range(len(am2)):
        sum_k += df.iloc[k]['n_k_2']
        n_im_list_2.append(sum_k)

    df['n_im_1'] = n_im_list
    df['n_im_2'] = n_im_list_2
    df['F1'] = df['n_im_1'] / df['n_k_1']
    df['F2'] = df['n_im_2'] / df['n_k_2']
    df['Module'] = abs(df['F1'] - df['F2'])
    df.loc['Сумма']= df.sum()
    display(df)
    
    m = max(df['Module'][:-2])
    nm = math.sqrt( df.iloc[-1]['n_k_1'] * df.iloc[-1]['n_k_2'] / (df.iloc[-1]['n_k_1'] + df.iloc[-1]['n_k_2']))
    print('nm' , nm)
    print('Максимальное число: ', m)
    print('Значение критерия равно: ', np.around(m * nm, 4) )

In [9]:
table(viborka_1, viborka_2)

Параметер равен:  0.8

,x_k,x_k+1,n_k_1,n_k_2,n_im_1,n_im_2,F1,F2,Module
0,0.0,1.0,515.0,545.0,515.0,545.0,1.000000,1.000000,0.000000
1,1.0,2.0,264.0,260.0,779.0,805.0,2.950758,3.096154,0.145396
2,2.0,3.0,117.0,110.0,896.0,915.0,7.658120,8.318182,0.660062
3,3.0,4.0,65.0,49.0,961.0,964.0,14.784615,19.673469,4.888854
4,4.0,5.0,21.0,18.0,982.0,982.0,46.761905,54.555556,7.793651
5,5.0,6.0,11.0,10.0,993.0,992.0,90.272727,99.200000,8.927273
6,6.0,7.0,2.0,6.0,995.0,998.0,497.500000,166.333333,331.166667
7,7.0,8.0,2.0,1.0,997.0,999.0,498.500000,999.000000,500.500000
8,8.0,9.0,3.0,1.0,1000.0,1000.0,333.333333,1000.000000,666.666667
Сумма,36.0,45.0,1000.0,1000.0,8118.0,8200.0,1492.761458,2351.176694,1520.748569

nm 22.360679774997898
Максимальное число:  500.5
Значение критерия равно:  11191.5202