# Экспоненциальное распределение Хи2 для сложной гипотезы

In [1]:
import random
import math
from math import e
import numpy as np
import pandas as pd

In [2]:
def make_expon_viborka(n, lam = 0.8):
    lst = []
    for i in range(n):
        r = random.random()
        x = -math.log(r,math.e) / lam
        lst.append(float('{:.3f}'.format(x)))
    
    return lst

In [3]:
#n = int(input()) # объем выборки
n = 100

In [4]:
my_list = make_expon_viborka(n)

In [5]:
my_set = list(set(my_list))
amount = []

for i in my_set:
    a = my_list.count(i)
    amount.append(a)


new_list = sorted(my_list)

number = 5 # количество чисел в интервале
count = 1 # cчетчик сколько чисел в интервале

final_interval = []
final_interval.append(new_list[0])

for i in new_list:
    if count == number:
        final_interval.append(i + 0.01)
        count = 0
    count += 1
#print(count)

print(final_interval)

final_interval_2 = final_interval[1:]
final_interval.pop(-1)
#final_interval_2.append(new_list[-1])

#print(new_list)
print(final_interval)
print(final_interval_2)



n_list = [number] * len(final_interval)
if len(n_list) != len(final_interval):
    n_list.append(count)


#print(list(map(len, [final_interval, final_interval_2, n_list])))
#print(new_list)

[0.01, 0.139, 0.192, 0.391, 0.515, 0.575, 0.6920000000000001, 0.794, 0.882, 0.983, 1.133, 1.321, 1.464, 1.573, 1.702, 1.805, 2.0239999999999996, 2.308, 2.71, 3.4019999999999997, 4.898]
[0.01, 0.139, 0.192, 0.391, 0.515, 0.575, 0.6920000000000001, 0.794, 0.882, 0.983, 1.133, 1.321, 1.464, 1.573, 1.702, 1.805, 2.0239999999999996, 2.308, 2.71, 3.4019999999999997]
[0.139, 0.192, 0.391, 0.515, 0.575, 0.6920000000000001, 0.794, 0.882, 0.983, 1.133, 1.321, 1.464, 1.573, 1.702, 1.805, 2.0239999999999996, 2.308, 2.71, 3.4019999999999997, 4.898]

# Сдеалаем свобдную таблицу

In [6]:
def table(): 
    x_mean = np.mean(my_set) # выборочное среднее 
    
    p = 1 / x_mean # оценка парметра p
    
    print('Оценка параметра равна: ',np.around(p, 3) )
    

    data = {'x_k': final_interval,
           'x_k+1': final_interval_2,
            'n_k': n_list}


    df = pd.DataFrame(data)
    
    df['P_k'] = np.around(e**(-p * df['x_k']) - e**(-p * df['x_k+1']), 3)
    df['n_k_2'] = np.around(n * df['P_k'], 3)
    df['Мера'] = np.around((df['n_k'] - df['n_k_2'])**2 / (df['n_k_2']), 3)
    df.loc['Сумма']= df.sum()
    display(df)

In [7]:
table()

Оценка параметра равна:  0.732

          x_k   x_k+1    n_k    P_k  n_k_2    Мера
0       0.010   0.139    5.0  0.089    8.9   1.709
1       0.139   0.192    5.0  0.034    3.4   0.753
2       0.192   0.391    5.0  0.118   11.8   3.919
3       0.391   0.515    5.0  0.065    6.5   0.346
4       0.515   0.575    5.0  0.029    2.9   1.521
5       0.575   0.692    5.0  0.054    5.4   0.030
6       0.692   0.794    5.0  0.043    4.3   0.114
7       0.794   0.882    5.0  0.035    3.5   0.643
8       0.882   0.983    5.0  0.037    3.7   0.457
9       0.983   1.133    5.0  0.051    5.1   0.002
10      1.133   1.321    5.0  0.056    5.6   0.064
11      1.321   1.464    5.0  0.038    3.8   0.379
12      1.464   1.573    5.0  0.026    2.6   2.215
13      1.573   1.702    5.0  0.028    2.8   1.729
14      1.702   1.805    5.0  0.021    2.1   4.005
15      1.805   2.024    5.0  0.040    4.0   0.250
16      2.024   2.308    5.0  0.043    4.3   0.114
17      2.308   2.710    5.0  0.047    4.7   0.019
18      2.710   3.402    5.0  0.055    5.5   0.045
19      3.402   4.898    5.0  0.055    5.5   0.045
Сумма  24.615  29.503  100.0  0.964   96.4  18.359